<?php
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in common-config.php and domserver-config.php

// Generated from 'domserver-static.php.in' on Tue Jan  3 13:09:35 WET 2017.

define('DOMJUDGE_VERSION', '5.2.0DEV');

define('BINDIR',      '/opt/domjudge/domserver/bin');
define('ETCDIR',      '/opt/domjudge/domserver/etc');
define('WWWDIR',      '/opt/domjudge/domserver/www');
define('LIBDIR',      '/opt/domjudge/domserver/lib');
define('LIBVENDORDIR','/opt/domjudge/domserver/lib/vendor');
define('LIBWWWDIR',   '/opt/domjudge/domserver/lib/www');
define('LIBSUBMITDIR','/opt/domjudge/domserver/lib/submit');
define('LOGDIR',      '/opt/domjudge/domserver/log');
define('RUNDIR',      '/opt/domjudge/domserver/run');
define('TMPDIR',      '/opt/domjudge/domserver/tmp');
define('SUBMITDIR',   '/opt/domjudge/domserver/submissions');

define('BASEURL',     'http://localhost/domjudge/');

define('SUBMITCLIENT_ENABLED', 'yes');
