#!/bin/sh

cat <<EOF
Bootstrapping brackets from Git repository sources...

Note that this script simply calls 'make dist'. Besides bootstrapping
the configure/build system, it also tries to build the PDF/HTML
documentation.

EOF

make dist
